version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: licitacoes_frontend
    environment:
      - VITE_API_URL=http://localhost:8100
      - VITE_APP_NAME=Sistema de Gerenciamento para Licitações
    ports:
      - "3100:80"
    networks:
      - frontend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  frontend_network:
    driver: bridge
