version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3100:80"
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment if you have a backend service
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=your-database-url
  #   restart: unless-stopped

networks:
  default:
    name: licitacoes-network
